helm:
  parameters:
  - name: argocd-image-updater-helm.image.name
    value: robinsabhaya/app
    forcestring: true
  - name: argocd-image-updater-helm.image.tag
    value: v1.0.17
    forcestring: true
