kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: argocd-helm-app
  namespace: argocd
  labels:
    name: argocd-helm-app
spec:
  project: default
  source:
    repoURL: https://github.com/RobinSabhaya/argocd-demo.git
    targetRevision: master
    path: k8s/argocd-helm/argocd-helm-chart
    # chart: argocd-helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
