kind: PersistentVolume
apiVersion: v1
metadata:
  name: app-pv
  namespace: app-namespace
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data"
