apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: my-image-updater
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: chai-app=robinsabhaya/chai-devops
    argocd-image-updater.argoproj.io/chai-app.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: "git:secret:argocd/git-creds"

spec:
  applicationRefs:
    - namePattern: "chai-app"
      images:
        - alias: "chai-app"
          imageName: "robinsabhaya/chai-devops:v1.0.8"
          commonUpdateSettings:
            updateStrategy: "semver"
  writeBackConfig:
    method: "git:secret:argocd/git-creds"
