kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: demo-app
  namespace: argocd
  labels:
    name: demo-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=robinsabhaya/app
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds
    argocd-image-updater.argoproj.io/demo-app.update-strategy: semver

spec:
  project: default
  source:
    repoURL: https://github.com/RobinSabhaya/argocd-demo.git
    targetRevision: master
    path: k8s/argocd-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
